### ISSUE TITLE
Epic: VCell ImageJ plugin MVP

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell-fiji#11]
Minimal Viable Product for a ImageJ plugin for VCell which can extract data from VCell servers using S3 and N5.

### Motivation
It would be powerful for many users to be able to compare spatial simulation data and microscopy data in a familiar shared environment.  The ImageJ application provides a platform where images can be viewed, processed and compared.  Making VCell spatial simulation data as images within ImageJ would be a convenient and familiar way to compare simulation results with spatial data. 

### Completion Criteria
- VCell Client users should be able to select simulation data to be made available to the VCell ImageJ Plugin as images for viewing and processing.
- The VCell ImageJ plugin should allow users to open these datasets within ImageJ without downloading the entire dataset.
- documentation should be provided.
- together, this capability should be a minimal viable product (MVP) for ImageJ/VCell integration mediated through the vcell servers.

## Essential Stories/Tasks
- [x] https://github.com/virtualcell/vcell/issues/1071
- [x] #19 
- [x] https://github.com/virtualcell/vcell/issues/1072
- [x] #13 

### Future
- #31

**Comment by AvocadoMoon** [comment]
Architecture of export is up in alpha, next steps.

- Make it easier to understand what you've exported and that this exists

**Comment by AvocadoMoon** [comment]
Direct line to most recent export can still have table, but the user who doesn't want to use it doesn't need to know about it.

**Comment by AvocadoMoon** [comment]
Was able to do a live demo at a conference with the tool. It works, but still isn't polished to the point of a finished product.
